# Generated by Django 6.0.6 on 2026-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='የሰራተኛው ሙሉ ስም')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='የፓስፖርት ቁጥር')),
                ('age', models.IntegerField(verbose_name='እድሜ')),
                ('skill', models.CharField(choices=[('domestic', 'የቤት ስራ'), ('driver', 'ሹፌር'), ('caregiver', 'ህጻናት/አረጋውያን ተንካባካቢ')], max_length=20, verbose_name='የሙያ አይነት')),
                ('status', models.CharField(choices=[('ready', 'ዝግጁ'), ('process', 'በሂደት ላይ'), ('deployed', 'የተላከ')], default='ready', max_length=10, verbose_name='የቪዛ/ሂደት ሁኔታ')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='የንብረቱ ስም')),
                ('property_type', models.CharField(choices=[('house', 'ቪላ/ቤት'), ('apartment', 'አፓርትመንት'), ('land', 'መሬት')], max_length=20, verbose_name='የንብረቱ አይነት')),
                ('location', models.CharField(max_length=100, verbose_name='ቦታ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, max_length=12, verbose_name='ዋጋ (በብር)')),
                ('status', models.CharField(choices=[('sale', 'የሚሸጥ'), ('rent', 'የሚከራይ')], max_length=10, verbose_name='ሁኔታ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ተጨማሪ ማብራሪያ')),
            ],
        ),
    ]
