# Generated by Django 6.0.6 on 2026-06-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='የንብረቱ ስም/ሞዴል')),
                ('category', models.CharField(choices=[('house_sale', 'የቤት/መሬት ሽያጭ (ሻጭና ገዢ)'), ('house_rent', 'የቤት ኪራይ (አከራይና ተከራይ)'), ('car_sale', 'የመኪና ሽያጭ')], max_length=30, verbose_name='የአገልግሎት አይነት')),
                ('location', models.CharField(max_length=100, verbose_name='ቦታ/አድራሻ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ዋጋ (በብር)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ዝርዝር መግለጫ (ለምሳሌ፦ ፎቅ፣ ማርሽ...)')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='የሰራተኛው ሙሉ ስም')),
                ('worker_type', models.CharField(choices=[('local', 'የሀገር ውስጥ ሰራተኛ (አሰሪና ሰራተኛ)'), ('foreign', 'የውጭ ሀገር ሰራተኛ (አሰሪና ሰራተኛ)')], max_length=20, verbose_name='የስራ ሁኔታ')),
                ('skill', models.CharField(choices=[('domestic', 'የቤት ስራ / ምግብ አሰራር'), ('driver', 'ሹፌር'), ('caregiver', 'ህጻናት/አረጋውያን ተንካባካቢ'), ('guard', 'ዘበኛ/ጥበቃ')], max_length=20, verbose_name='የሙያ አይነት')),
                ('age', models.IntegerField(verbose_name='እድሜ')),
                ('passport_or_id', models.CharField(max_length=30, verbose_name='የፓስፖርት ወይም የፊንገር/መታወቂያ ቁጥር')),
                ('price_or_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='የሚፈልጉት ደመወዝ / የኤጀንሲ ዋጋ')),
            ],
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
