# Generated by Django 6.0.6 on 2026-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_asset_worker_delete_candidate_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='የንብረቱ ምስል (ፎቶ)'),
        ),
        migrations.AddField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(default='0900000000', max_length=20, verbose_name='ባለቤት/ሻጭ ስልክ ቁጥር (ለአድሚን ብቻ)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(default='0900000000', max_length=20, verbose_name='የሰራተኛው ስልክ ቁጥር (ለአድሚን ብቻ)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='ዝርዝር መግለጫ'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='passport_or_id',
            field=models.CharField(max_length=30, verbose_name='የፓስፖርት ወይም የመታወቂያ ቁጥር'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='price_or_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ደመወዝ / የኤጀንሲ ዋጋ'),
        ),
    ]
