# Generated by Django 6.0.6 on 2026-06-27 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asset_image_asset_phone_number_worker_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='የተለጠፈበት ቀን'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-06-27', verbose_name='የተለጠፈበት ቀን'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='ባለቤት/ሻጭ ስልክ ቁጥር'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='የሰራተኛው ስልክ ቁጥር'),
        ),
    ]
