# Generated by Django 6.0.6 on 2026-06-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset_created_at_worker_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_name', models.CharField(max_length=100, verbose_name='የቀጣሪው/አሰሪው ሙሉ ስም')),
                ('job_type', models.CharField(choices=[('local', 'የሀገር ውስጥ'), ('foreign', 'የውጭ ሀገር')], max_length=20, verbose_name='የስራ ሁኔታ')),
                ('required_skill', models.CharField(choices=[('domestic', 'የቤት ስራ / ምግብ አሰራር'), ('driver', 'ሹፌር'), ('caregiver', 'ህጻናት/አረጋውያን ተንካባካቢ'), ('guard', 'ዘበኛ/ጥበቃ')], max_length=20, verbose_name='የሚፈለገው ሙያ')),
                ('gender_preference', models.CharField(choices=[('M', 'ወንድ'), ('F', 'ሴት'), ('any', 'አይለይም')], max_length=20, verbose_name='የፆታ ምርጫ')),
                ('offered_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='የሚከፍሉት ደመወዝ (ብር)')),
                ('location', models.CharField(max_length=100, verbose_name='የስራ ቦታ/አድራሻ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='የአሰሪው ስልክ ቁጥር (ለአድሚን ብቻ)')),
                ('other_requirements', models.TextField(blank=True, null=True, verbose_name='ተጨማሪ መስፈርቶች (ካሉ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='የተመዘገበበት ቀን')),
            ],
        ),
    ]
