# Generated by Django 6.0.6 on 2026-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employerrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('house_sale', 'የቤት/መሬት ሽያጭ (ሻጭና ገዢ)'), ('house_rent', 'የቤት ኪራይ (አከራይና ተከራይ)'), ('car_sale', 'የመኪና ሽያጭ'), ('land_sale', 'የቦታ ሽያጭ')], max_length=30, verbose_name='የአገልግሎት አይነት'),
        ),
    ]
