# Generated by Django 6.0.6 on 2026-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='ክፍያ ተፈጽሟል?'),
        ),
        migrations.AddField(
            model_name='employerrequirement',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='ክፍያ ተፈጽሟል?'),
        ),
        migrations.AddField(
            model_name='worker',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='ክፍያ ተፈጽሟል?'),
        ),
        migrations.AlterField(
            model_name='employerrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='የተለጠፈበት ቀን'),
        ),
    ]
