# Generated by Django 6.0.6 on 2026-06-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asset_is_paid_employerrequirement_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='የእይታ ብዛት'),
        ),
        migrations.AddField(
            model_name='employerrequirement',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='የእይታ ብዛት'),
        ),
        migrations.AddField(
            model_name='worker',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='የእይታ ብዛት'),
        ),
        migrations.AlterField(
            model_name='employerrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='የተመዘገበበት ቀን'),
        ),
    ]
